/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.icl.telegram.bot;

import org.telegram.telegrambots.ApiContextInitializer;
import org.telegram.telegrambots.bots.DefaultBotOptions;
import org.telegram.telegrambots.bots.DefaultBotOptions.ProxyType;
import org.telegram.telegrambots.meta.ApiContext;
import org.telegram.telegrambots.meta.TelegramBotsApi;

public class StartPoint {

    public static void main(String[] args) {
		try {
			ApiContextInitializer.init();
			TelegramBotsApi botsApi = new TelegramBotsApi();
			DefaultBotOptions defaultBotOptions = ApiContext.getInstance(DefaultBotOptions.class);
			defaultBotOptions.setProxyHost("64.227.2.136");
			defaultBotOptions.setProxyPort(8080);
			defaultBotOptions.setProxyType(ProxyType.HTTP);
			botsApi.registerBot(new ICLTelegramBot(defaultBotOptions));
		} catch (Exception ex) {
			ex.printStackTrace();
		}

	}
}
